In [1]:
import numpy as np

In [2]:
#list
numbers=[1,2,3,4,5,6,7,8,9]

In [3]:
numbers

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
numbers[3]

4

In [5]:
a=np.array(numbers)

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [8]:
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
print(a[1])

2


In [10]:
a[3]

np.int64(4)

In [11]:
len(a)

9

In [12]:
#reshape
a.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
#reshape
a.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [14]:
#reshape
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a[3:6]

array([4, 5, 6])

In [16]:
a=a.reshape(3,3)

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a[2,2]

np.int64(9)

In [19]:
a[1,1]

np.int64(5)

In [20]:
a[1:,0:2]

array([[4, 5],
       [7, 8]])

In [21]:
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones(15,dtype=int).reshape(5,3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
b=np.arange(12)

In [25]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
b+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [27]:
b=b+5

In [28]:
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [29]:
a+3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
a-3

array([[-2, -1,  0],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [31]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
print(a[1][2]<b[5])

True


In [33]:
b=np.arange(1,13).reshape(3,4)

In [34]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
c=a**3

In [36]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
c

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]])

In [38]:
a+c

array([[  2,  10,  30],
       [ 68, 130, 222],
       [350, 520, 738]])

In [39]:
a*b

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [40]:
d=b[0:,0]

In [41]:
e=d.reshape(3,1)

In [42]:
d

array([1, 5, 9])

In [43]:
a+d

array([[ 2,  7, 12],
       [ 5, 10, 15],
       [ 8, 13, 18]])

In [44]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
e

array([[1],
       [5],
       [9]])

In [46]:
#(3,3) operator (1,3)

In [47]:
a+e

array([[ 2,  3,  4],
       [ 9, 10, 11],
       [16, 17, 18]])

In [48]:
import random

In [49]:
val=np.random.randint(20,50,size=10).reshape(5,2)

In [50]:
val

array([[30, 35],
       [36, 26],
       [27, 34],
       [29, 33],
       [38, 42]], dtype=int32)

In [51]:
val2=np.random.random((4,10))

In [52]:
val2

array([[0.9115981 , 0.94847612, 0.49614242, 0.18878483, 0.26728085,
        0.87326178, 0.36225766, 0.41187889, 0.8301503 , 0.17934937],
       [0.49515131, 0.78459231, 0.39211591, 0.59128261, 0.44912072,
        0.24866284, 0.94813577, 0.72752044, 0.09486838, 0.0467596 ],
       [0.74154819, 0.31396109, 0.99887714, 0.11770905, 0.88699792,
        0.35270983, 0.28432339, 0.66883845, 0.77657907, 0.19121482],
       [0.97131407, 0.11086446, 0.41893956, 0.5078126 , 0.29701304,
        0.3990545 , 0.19482594, 0.79727201, 0.89258337, 0.15238685]])

In [62]:
a=np.random.randint(2,10,size=4).reshape(2,2)

In [55]:
a

array([[35, 51, 67, 33],
       [88, 49, 56, 65],
       [60, 98, 35, 67],
       [77, 20, 80, 47]], dtype=int32)

In [56]:
np.linalg.inv(a)

array([[ 0.54895047,  0.95579899, -0.5854848 , -0.87265571],
       [ 0.32720922,  0.53225539, -0.3230908 , -0.50526426],
       [-0.05796227, -0.13385404,  0.07193388,  0.12327015],
       [-0.93992317, -1.56453845,  0.9742433 ,  1.45613113]])

In [65]:
a[1][1]=6

In [66]:
np.linalg.det(a)

np.float64(2.000000000000001)

2x+3y=5
4x+y=6

In [71]:
A=np.array([[2,1],[-3,6]])
B=np.array([5,0])

In [72]:
X=np.linalg.solve(A,B)

In [73]:
X

array([2., 1.])

In [83]:
a=np.eye(4,dtype=int)

In [84]:
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [77]:
a

array([[4607182418800017408,                   0,                   0,
                          0],
       [                  0, 4607182418800017408,                   0,
                          0],
       [                  0,                   0, 4607182418800017408,
                          0],
       [                  0,                   0,                   0,
        4607182418800017408]])